version: "3.8"

services:
  postgres:
    container_name: jopiter_postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "jopiter"
      POSTGRES_DB: "jopiter"
  jopiter:
    container_name: jopiter_backend
    image: docker.io/library/jopiter:1.1.0
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/jopiter