version: "3.8"

services:
  postgres:
    container_name: jopiter_postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "jopiter"
      POSTGRES_DB: "jopiter"