version: "3.8"

services:
  postgres:
    container_name: jopiter_postgres
    image: postgres
    expose:
      - "5432"
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "jopiter"
      POSTGRES_DB: "jopiter"
  jopiter:
    container_name: jopiter_backend
    image: docker.io/library/jopiter:2.2.1
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/jopiter