name: Release
on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'

jobs:
  release:
    env:
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check
        run: ./gradlew check
      - name: Create ShadowJar
        run: ./gradlew shadowJar
      - name: Deploy to Beanstalk
        uses: einaregilsson/beanstalk-deploy@v16
        with:
          application_name: jopiter backend
          environment_name: JopiterBackend-env
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: us-east-1
          version_label: ${{ github.run_number }}
          deployment_package: build/libs/jopiter-backend-all.jar